title:       Bin Wang
name: Bin Wang
description: This is my personal blog about computer since and technology, and my life.
paginate: 15


safe:        false
serve:      false
port: 4000
baseurl:    /
url: http://www.binwang.me

category_title_prefix: ''

source:      .
destination: ./_site
plugindir:     ./_plugins
plugins: [jekyll-paginate]

future:      true
lsi:         false
markdown:    kramdown
permalink:   /:year-:month-:day-:title.html

collections:
  category:
    output: true

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: coderay
  input: GFM

syntax_highlighter_opts:
  wrap: div
  line_numbers: table
  line_numbers_start: 1
  tab_width: 4
  bold_every: 10
  css: style

gems: [jekyll-paginate]
