title:       Bin Wang
description: This is my personal blog about computer since and technology, and my life.
paginate: 15

safe:        false
serve:      false
port: 4000
baseurl:    /
url: http://www.binwang.me

category_title_prefix: ''

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
markdown:    kramdown
permalink:   /:year-:month-:day-:title.html


rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true
  input: GFM
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: table
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

