# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "jekyll", "~> 4.3"

gem "jekyll-paginate", "~> 1.1"

gem "jekyll-feed", "~> 0.17.0"

gem "erb", "~> 4.0"

gem "ostruct", "~> 0.6.1"

gem "base64", "~> 0.2.0"

gem "logger", "~> 1.6"

gem "csv", "~> 3.3"
